repos:
- repo: local
  hooks:
    - id: flake8
      args: [--config=./tox.ini]
      name: flake8
      entry: flake8
      language: system
      types: [ python ]
      require_serial: true
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: system
      types_or: [ cython, pyi, python ]
      args: [ "--filter-files" ]
    - id: commitizen
      name: commitizen
      entry: cz check
      args: [ --allow-abort, --commit-msg-file ]
      language: system
      stages: [ commit-msg ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
      args: [--maxkb=1500000]
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
